# Generated by Django 5.2.5 on 2025-09-02 19:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Note title', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('raw_content', models.TextField(blank=True, help_text='Raw transcribed content from speech-to-text')),
                ('key_points', models.JSONField(default=list, help_text='AI-generated key points as array of strings')),
                ('detailed_notes', models.TextField(blank=True, help_text='AI-generated detailed and structured notes')),
                ('audio_file_path', models.CharField(blank=True, help_text='Path to original audio file', max_length=500)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('processing', 'AI Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Associated course', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.course')),
                ('user', models.ForeignKey(help_text='Note owner', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
